title: Vantibyte
url: "https://vantibyte.com"
baseurl:
# google_analytics_key: UA-176823557-1

description: Provider of modern broadcasting tools

author:
  name: Vantibyte
  email:
  # twitter: vantibyte

timezone: Etc/UTC

# Should we generate the collections from markdown?
collections:
  products:
    output: true
  clients:
    output: false

permalink: pretty

plugins:
  - "jekyll-seo-tag"
  - "jekyll-sitemap"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

include: 
  - ".well-known"

defaults:
  # Set these pages to use a specific layout
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      _options:
        image_path:
          width: 2000
          height: 2000
  # Set this logo as the default for cards/embeds/opengraph
  - scope:
      path: ""
    values:
      image: /images/vblogo.png
  # Disable images being added to the sitemap
  - scope:
      path: "images/*"
    values:
      sitemap: false
  # Set .well-known to use no layout
  - scope:
      path: ".well-known/*"
    values:
      layout: "none"
  # Set pages to use the "page" layout by default
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  # Set the index page to use the default layout
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  # - Twitter
  - Reaired
  - Discord
  - Twitch

# Do some minification
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false